FROM registry.access.redhat.com/jboss-eap-6/eap64-openshift:1.3

MAINTAINER Siamak Sadeghianfar <ssadeghi@redhat.com>

RUN curl -L -o /opt/eap/standalone/deployments/ROOT.war https://www.dropbox.com/s/p4m7wdarfda9ibo/helloworld.war?dl=1 

EXPOSE 8080